# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_title', models.CharField(max_length=20)),
                ('ms_content', models.TextField()),
                ('ms_pub_date', models.DateTimeField()),
            ],
        ),
    ]
