# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=20)),
                ('art_pub_date', models.DateTimeField(verbose_name='article published')),
                ('art_content', models.TextField()),
                ('art_type', models.CharField(max_length=20)),
                ('art_view_num', models.IntegerField()),
                ('art_reply_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_title', models.CharField(max_length=40)),
                ('dr_content', models.TextField()),
                ('dr_pub_date', models.DateTimeField()),
                ('dr_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_title', models.CharField(max_length=20)),
                ('rp_content', models.TextField()),
                ('rp_pub_date', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
    ]
